# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

variables:
- group: 'variables'
 

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    jdkVersionOption: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- bash: |
    ls -l > list.log
    less list.log

- task: DownloadSecureFile@1
  inputs:
    secureFile: '$(Keystore_FileName)'


- task: Build-2Secure@0
  inputs:
    Platform: 'android'
    Sign: 'signOnAppdome'
    Token: '$(APPDOME_API_KEY)'
    KeystoreFile: '$(Keystore_FileName)'
    KeystorePass: '$(Keystore_Password)'
    KeystoreAlias: 'appdome'
    KeyPass: '$(Keystore_Password)'
    FusionSetId: 'ac111720-c7d7-11ec-9c26-bb3f9e9d83c4'
    TeamId: '0f2b8ec0-804e-11ec-8707-97e61e2ab1dd'
    App: $(system.defaultworkingdirectory)/app/build/outputs/apk/release/app-release-unsigned.apk

