# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

variables:
- group: 'variables'
 

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- script: echo $(APPDOME_API_KEY)
- script: echo $(Keystore_Password)

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    jdkVersionOption: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- bash: |
    cd app/build/outputs/apk/debug/
    ls -l 
    echo $(APPDOME_API_KEY)
    
- task: DownloadSecureFile@1
  name: keystore
  inputs:
    secureFile: '$(Keystore_FileName)'


- task: Build-2Secure@0
  inputs:
    Platform: 'android'
    Sign: 'signOnAppdome'
    Token: '$(APPDOME_API_KEY)'
    BuildToTest: None
    BuildWithLogs: false
    KeystoreFile: '$(keystore.secureFilePath)'
    KeystorePass: '$(Keystore_Password)'
    KeystoreAlias: 'appdome'
    KeyPass: '$(Keystore_Password)'
    FusionSetId: 'ac111720-c7d7-11ec-9c26-bb3f9e9d83c4'
    TeamId: '0f2b8ec0-804e-11ec-8707-97e61e2ab1dd'
    App: app/build/outputs/apk/debug/app-debug.apk

- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: '$(Build.ArtifactStagingDirectory)'
   ArtifactName: 'Appdome Protected App'

