# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: CmdLine@2
    inputs:
      script: |
        apt-get update && apt-get install -y curl
        git clone https://github.com/Appdome/appdome-api-python.git
        ls -l


