name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
      
   # - name: Upload APK
   #   uses: actions/upload-artifact@v1
   #   with:
   #     name: app-release-unsigned.apk
   #     path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: List Files Action
      uses: mirko-felice/list-files-action@v3.0.5
      with:
        path: app/build/outputs/apk/release/

       
      
      
      
#name: Appdome build-2secure
#  appdome:
#    name: Protect App with Appdome
#    needs: build
#    runs-on: ubuntu-latest
    
#    steps:
    - name: Appdome build-2secure
      uses: Appdome/github_build-2secure@1.1.1
      with:
        APP_FILE: app/build/outputs/apk/release/app-release-unsigned.apk
        TEAM-ID: 0f2b8ec0-804e-11ec-8707-97e61e2ab1dd
        FUSION_SET_ID: ac111720-c7d7-11ec-9c26-bb3f9e9d83c4
        SIGN_OPTIONS: "SIGN_ON_APPDOME"
        #BUILD_WITH_LOGS: true - Optional
        #SECOND_OUTPUT: true - Optional
        #BUILD_TO_TEST: "lambdatest" | "bitbar" | "browserstack" | "saucelabs" - Optional
        APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
        KEYSTORE_FILE: ${{secrets.KEYSTORE_BASE64}}
        KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        KEYSTORE_ALIAS: ${{secrets.KEYSTORE_ALIAS}}
        KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASS}}      

      
      
      
      
